-- 동남아 다이빙 목적지 데이터를 추가한다: 필리핀 3곳(사방·투바타하·두마게테), 말레이시아 2곳(페리헨티·티오만),
-- 인도네시아 2곳(알로르·투람벤), 신규 국가 베트남(냐짱)·미얀마(메르귀 군도) 각 1곳.
-- docs/decisions/travel-data-source.md 참고 (2026년 8월 웹 조사 기준 큐레이션 데이터).

insert into public.destinations
  (id, name, country, region, distance_km, lat, lng, flight, local_transfer, local_transfer_short, styles, condition, reason, dive_prices, gear, liveaboard, lodging, maps)
values
  ('puerto-galera', '푸에르토 갈레라 · 사방비치', '필리핀', '필리핀', 2600, 13.509, 120.974,
    '{"transfer":"직항","priceMin":45,"priceMax":65,"destinationAirport":"마닐라"}'::jsonb,
    '마닐라 공항에서 육로로 바탕가스 항구까지 약 2～3시간, 페리로 사방까지 약 1～1.5시간이 걸립니다.', '육로+페리 4시간',
    ARRAY['매크로','드리프트','초급자'],
    '{"optimal":[12,1,2,3,4],"good":[5,6,10,11],"poor":[7,8,9]}'::jsonb,
    '{"optimal":"12～4월은 아미한(북동 계절풍) 시기로 파도가 잔잔하고 시야가 좋아 사방 전 지역 다이빙에 최적입니다.","good":"6월, 10～11월은 건기와 우기 사이 전환기로 비가 간헐적으로 내리지만 만 지형이 파도를 막아줘 다이빙은 대체로 무리 없이 가능합니다.","poor":"7～9월은 하바가트(남서 계절풍)·태풍 시즌으로 바탕가스-사방 간 페리가 결항되는 날이 있고, 외해 포인트는 파도와 시야 저하가 심해집니다."}'::jsonb,
    ARRAY[3.8,3.5,3.3,3], 2, null,
    '{"shop":[3,6],"separate":[2.5,8]}'::jsonb,
    'https://www.google.com/maps/search/sabang+puerto+galera+dive+shop'),

  ('tubbataha', '투바타하 리프', '필리핀', '필리핀', 3178, 8.85, 119.87,
    '{"transfer":"경유","priceMin":35,"priceMax":65,"transferAirport":"마닐라","destinationAirport":"푸에르토프린세사"}'::jsonb,
    '푸에르토프린세사 공항에서 베이워크 부두까지 차량으로 약 15～20분, 리브어보드사에서 픽업 후 부두에서 바로 승선합니다.', '차량 20분',
    ARRAY['대물','조류','드리프트'],
    '{"optimal":[4,5],"good":[3,6],"poor":[1,2,7,8,9,10,11,12]}'::jsonb,
    '{"optimal":"4～5월은 투바타하 시즌 중 최고 컨디션으로 시야 30～40m, 잔잔한 바다, 수온 27～29도를 보이며 상어·만타 등 대물 조우율과 조류 다이빙 퀄리티가 가장 높습니다.","good":"3월 말과 6월 초는 국립공원이 개장·폐장하는 시즌의 초입과 끝자락으로 다이빙 자체는 가능하지만 크로싱에서 스웰이 다소 있을 수 있습니다.","poor":"투바타하 국립공원은 몬순 시즌인 7월부터 다음해 3월 중순까지 관리사무소가 공식 폐쇄해 리브어보드 운항 및 입도 자체가 불가능합니다."}'::jsonb,
    ARRAY[9.5,8.5,8,7.5], 3.5, '{"months":[3,4,5,6],"priceMin":30,"priceMax":65}'::jsonb,
    '{"shop":[6,14],"separate":[5,16]}'::jsonb,
    'https://www.google.com/maps/search/tubbataha+reef+liveaboard'),

  ('dumaguete-apo', '두마게테 · 아포섬', '필리핀', '필리핀', 3145, 9.07, 123.27,
    '{"transfer":"경유","priceMin":65,"priceMax":110,"transferAirport":"세부","destinationAirport":"두마게테"}'::jsonb,
    '두마게테 공항에서 다우인 다이빙샵까지 육로로 약 30～40분, 아포섬까지는 다시 보트로 20～30분 이동합니다.', '육로 40분+보트 20분',
    ARRAY['매크로','드리프트','대물'],
    '{"optimal":[1,2,3,4,5],"good":[6,10,11,12],"poor":[7,8,9]}'::jsonb,
    '{"optimal":"1～5월 건조기에는 파도가 잔잔하고 시야가 20～30m로 가장 좋으며 수온(27～29도)도 다이빙에 적합합니다.","good":"6월과 10～12월은 우기 초입 또는 회복기로 다이빙은 가능하지만 시야와 파도 상태가 건기보다 다소 떨어집니다.","poor":"7～9월 몬순 성수기에는 강풍과 너울로 바다가 거칠어지고 시야도 10～20m로 낮아집니다."}'::jsonb,
    ARRAY[6,5.3,4.8,4.3], 3, null,
    '{"shop":[4.5,15],"separate":[2.5,12]}'::jsonb,
    'https://www.google.com/maps/search/Apo+Island+Dumaguete+dive+shop'),

  ('perhentian', '페리헨티 섬', '말레이시아', '말레이시아', 4253, 5.9, 102.73,
    '{"transfer":"경유","priceMin":45,"priceMax":70,"transferAirport":"쿠알라룸푸르","destinationAirport":"코타바루"}'::jsonb,
    '코타바루 공항에서 차량으로 꾸알라 브사웃 선착장까지 약 1시간, 선착장에서 스피드보트로 페리헨티 섬까지 30～45분 이동합니다.', '차+보트 1.5시간',
    ARRAY['초급자','매크로'],
    '{"optimal":[5,6,7,8],"good":[3,4,9,10],"poor":[11,12,1,2]}'::jsonb,
    '{"optimal":"5～8월은 우기 이후 파도가 가장 잔잔하고 가시거리가 최대 30m까지 나와 다이빙에 최적입니다.","good":"3～4월과 9～10월은 몬순 전후 환절기로 컨디션은 대체로 양호하지만 최적기보다 시야가 다소 떨어질 수 있습니다.","poor":"11～2월은 몬순 시즌으로 파도가 거세지고 대부분의 리조트·다이빙샵이 문을 닫아 섬 자체가 사실상 폐쇄됩니다."}'::jsonb,
    ARRAY[3,2.7,2.4,2.1], 1.3, null,
    '{"shop":[2,3.5],"separate":[2.5,6]}'::jsonb,
    'https://www.google.com/maps/search/perhentian+islands+dive+shop'),

  ('tioman', '티오만 섬', '말레이시아', '말레이시아', 4603, 2.81, 104.16,
    '{"transfer":"직항","priceMin":40,"priceMax":70,"destinationAirport":"쿠알라룸푸르"}'::jsonb,
    '쿠알라룸푸르 공항에서 육로로 메르싱 또는 탄중 게목 항구까지 약 4～4.5시간 이동한 뒤, 페리로 티오만 섬까지 약 1.5～2시간이 걸립니다.', '육로+페리 6시간',
    ARRAY['초급자','매크로','대물'],
    '{"optimal":[3,4,5,9,10],"good":[6,7,8],"poor":[11,12,1,2]}'::jsonb,
    '{"optimal":"3～5월과 9～10월은 몬순 전후 환절기로 바다가 잔잔하고 시야가 15～30m까지 확보되는 최적의 다이빙 시즌입니다.","good":"6～8월은 본격 우기는 아니지만 남서 몬순 영향으로 간간이 스콜과 스웰이 발생해 시야가 다소 줄어들 수 있습니다.","poor":"11～2월은 북동 몬순으로 강풍과 높은 파도가 몰아쳐 대부분의 다이빙샵과 리조트가 휴업하고 페리 운항도 중단됩니다."}'::jsonb,
    ARRAY[3.6,3.2,3,2.7], 1.5, null,
    '{"shop":[2.5,4.5],"separate":[3,8]}'::jsonb,
    'https://www.google.com/maps/search/tioman+island+dive+shop'),

  ('alor', '알로르', '인도네시아', '인도네시아', 5080, -8.22, 124.57,
    '{"transfer":"경유","priceMin":95,"priceMax":140,"transferAirport":"발리(덴파사르)","destinationAirport":"칼라바히"}'::jsonb,
    '칼라바히 말리 공항에서 다이빙 리조트까지 차량으로 15～40분, 리조트에 따라 보트 이동이 추가됩니다.', '차량 30분',
    ARRAY['조류','대물','매크로'],
    '{"optimal":[4,5,6,9,10,11],"good":[7,8],"poor":[12,1,2,3]}'::jsonb,
    '{"optimal":"4～6월과 9～11월은 판타르 해협의 강한 조류와 함께 해머헤드샤크 등 대물 조우 확률이 가장 높고, 시야도 25～40m로 한 해 중 가장 좋습니다.","good":"7～8월은 남동몬순 영향으로 수온이 28도 이상 오르고 시야도 30m 이상으로 좋지만, 대물·조류 활동은 피크 시즌보다 다소 약합니다.","poor":"12～3월 우기에는 강수로 인한 부유물 유입과 해상 컨디션 악화로 일부 다이빙 포인트 접근이 어렵고 시야도 15m 이하로 떨어질 수 있습니다."}'::jsonb,
    ARRAY[11,10.3,9.6,8.8], 2.8, '{"months":[4,5,6,7,8,9,10,11],"priceMin":46,"priceMax":66}'::jsonb,
    '{"shop":[9,18],"separate":[2.5,6]}'::jsonb,
    'https://www.google.com/maps/search/alor+dive+resort+kalabahi'),

  ('tulamben', '발리 · 투람벤', '인도네시아', '인도네시아', 5300, -8.27, 115.59,
    '{"transfer":"직항","priceMin":60,"priceMax":85,"destinationAirport":"발리"}'::jsonb,
    '발리 응우라라이 공항에서 투람벤까지 육로로 산길과 해안도로를 거쳐 약 2.5～3시간이 소요됩니다.', '육로 3시간',
    ARRAY['초급자','매크로'],
    '{"optimal":[4,5,6,7,10,11],"good":[8,9,12],"poor":[1,2,3]}'::jsonb,
    '{"optimal":"4～7월과 10～11월 건기 절정기엔 시야가 최대 40m까지 확보되고 만 지형이 잔잔해 리버티 난파선 전경을 온전히 즐길 수 있습니다.","good":"8～9월은 여전히 건기라 다이빙 자체는 쾌적하지만 성수기 관광객이 몰려 혼잡하고, 12월은 우기 초입이라 오전 시야는 대체로 양호합니다.","poor":"1～3월 우기 절정기엔 빗물 유입으로 시야가 5～15m까지 떨어지고 컨디션이 가장 불안정합니다."}'::jsonb,
    ARRAY[4.8,4,3.5,3], 1.8, null,
    '{"shop":[4,9],"separate":[3,12]}'::jsonb,
    'https://www.google.com/maps/search/tulamben+dive+shop'),

  ('nha-trang', '냐짱(나트랑)', '베트남', '베트남', 3310, 12.24, 109.19,
    '{"transfer":"직항","priceMin":30,"priceMax":65,"destinationAirport":"나트랑"}'::jsonb,
    '깜란 국제공항에서 나트랑 시내까지 택시나 그랩으로 약 40～60분, 공항버스도 이용 가능합니다.', '택시 40～60분',
    ARRAY['초급자','매크로'],
    '{"optimal":[1,2,3,4,5,6,7,8],"good":[9,12],"poor":[10,11]}'::jsonb,
    '{"optimal":"1～8월 건기에는 파도가 잔잔하고 시야가 좋아 초급자 교육과 펀다이빙 모두에 가장 좋은 시기입니다.","good":"9월과 12월은 우기의 시작·끝자락으로 비가 간간이 내리지만 다이빙 컨디션에 큰 지장은 없습니다.","poor":"10～11월은 우기 중 강수량이 가장 많고 간혹 태풍의 영향권에 들어 시야가 나빠지며 해상 액티비티가 취소되기도 합니다."}'::jsonb,
    ARRAY[3.5,3.1,2.8,2.5], 1, null,
    '{"shop":[2,3.5],"separate":[2.5,7]}'::jsonb,
    'https://www.google.com/maps/search/nha+trang+dive+shop'),

  ('mergui', '메르귀 군도', '미얀마', '미얀마', 4154, 11.3, 98,
    '{"transfer":"경유","priceMin":65,"priceMax":95,"transferAirport":"방콕","destinationAirport":"라농"}'::jsonb,
    '라농 공항에서 차량으로 약 20～30분 이동해 선착장에 도착한 뒤, 코타웅 국경에서 미얀마 입출국 수속을 마치고 리브어보드에 승선합니다.', '차량 30분+통관',
    ARRAY['대물','조류','드리프트'],
    '{"optimal":[12,1,2,3],"good":[11,4],"poor":[5,6,7,8,9,10]}'::jsonb,
    '{"optimal":"12～3월은 건기 절정으로 파도가 가장 잔잔하고 시야가 가장 좋아 리브어보드 운항이 집중되는 시기입니다.","good":"11월과 4월은 시즌 시작과 종료 시점이라 리브어보드 선택지가 줄고 기상이 다소 불안정할 수 있습니다.","poor":"5～10월 우기에는 국립공원·특별구역 진입이 제한되어 리브어보드가 전면 운항을 중단합니다."}'::jsonb,
    ARRAY[7.5,6.8,6.2,5.8], 2, '{"months":[11,12,1,2,3,4],"priceMin":28,"priceMax":45}'::jsonb,
    '{"shop":[4,7],"separate":[5,10]}'::jsonb,
    'https://www.google.com/maps/search/mergui+archipelago+liveaboard');
